background_opacity 0.85
background #2D2D2D
foreground #D3D7CF

selection_background #555753
selection_foreground #FFFFFF

cursor #8AE234

color0 #2E3436
color1 #CC0000
color2 #4E9A06
color3 #C4A000
color4 #3465A4
color5 #75507B
color6 #06989A
color7 #D3D7CF
startup_session ~/.config/kitty/session.conf

remember_window_size no
initial_window_width 1920
initial_window_height 1080
