layout grid

launch sh -c "fastfetch --logo arch; exec bash"

launch sh -c "pokemon-colorscripts -n charizard --no-title; exec bash"

launch sh -c "btop; exec bash"

launch sh -c "cmatrix -C cyan; exec bash"
